[workspace]
resolver = "2"
members = ["lib"]

[package]
name = "deskpi"
build = "build.rs"
version = "0.1.0"
edition = "2021"

[dependencies]
raylib = { version = "3.7" }
hot-lib-reloader = { version = "^0.6", features = ["verbose"], optional = true }
lib = { path = "lib" }
tokio = { version = "1.20.1", features = ["full"] }
simple_logger = "^4.0.0"

[features]
default = []
reloader = ["lib/reloader", "raylib/nobuild", "dep:hot-lib-reloader"]
