[config]
skip_core_tasks = true

[tasks.default]
dependencies = ["build"]

[tasks.start]
workspace = false
command = "cargo"
args = ["runcc", "-c"]
dependencies = ["build"]

[tasks.build]
dependencies = ["raylib_build", "bin_build", "raylib_copy", "raylib_cross_docker"]

[tasks.bin_build]
command = "cargo"
args = ["build"]

[tasks.clean]
command = "cargo"
args = ["clean"]
dependencies = ["raylib_clean"]

[tasks.raylib_build]
script = "cmake -S raylib -B raylib-build -DBUILD_SHARED_LIBS=ON -DBUILD_EXAMPLES=OFF && cd raylib-build && make"

[tasks.raylib_copy]
script = "cd raylib-build && cp raylib/libraylib.3.5.0.dylib \"$CARGO_MAKE_CRATE_TARGET_DIRECTORY/debug/libraylib.351.dylib\""

[tasks.raylib_clean]
script = "rm -rf raylib-build"

[tasks.raylib_cross_docker]
script = "docker build -t raylib_rs_env ."
