[config]
skip_core_tasks = true

[tasks.default]
dependencies = ["build"]

[tasks.start]
workspace = false
command = "cargo"
args = ["runcc", "-c"]
dependencies = ["build"]

[tasks.build]
workspace = false
dependencies = [
    "patch",
    "glslcc_build",
    "raylib_build",
    "shaders_build",
    "bin_build",
    "raylib_copy",
]

[tasks.clean]
workspace = false
dependencies = [
    "pi_clean",
    "glslcc_clean",
    "raylib_clean",
    "shaders_clean",
    "bin_clean",
    "python_clean",
    "ansible_clean",
]

[tasks.deploy]
workspace = false
dependencies = [
    "patch",
    "glslcc_build",
    "shaders_build",
    "pi_build",
    "python_install",
    "ansible_install",
    "ansible_playbook",
]

[tasks.deploy_code]
workspace = false
dependencies = [
    "pi_build",
    "ansible_playbook_code",
]

[tasks.patch]
workspace = false
command = "cargo"
args = ["patch-crate"]

[tasks.bin_build]
workspace = false
command = "cargo"
args = ["build"]

[tasks.bin_clean]
workspace = false
command = "cargo"
args = ["clean"]

[tasks.raylib_build]
workspace = false
script = '''
cmake -S external/raylib/src -B external/raylib/build -DBUILD_SHARED_LIBS=ON -DBUILD_EXAMPLES=OFF
cd external/raylib/build
CFLAGS="-DSUPPORT_FILEFORMAT_JPG=1" make
'''

[tasks.raylib_copy]
workspace = false
script = '''
cd external/raylib/build
cp raylib/libraylib.3.5.0.dylib "$CARGO_MAKE_CRATE_TARGET_DIRECTORY/debug/libraylib.351.dylib"
'''

[tasks.raylib_clean]
workspace = false
script = "rm -rf external/raylib/build"

[tasks.glslcc_build]
workspace = false
script = '''
cmake -S external/glslcc/src -B external/glslcc/build
cd external/glslcc/build
make
'''

[tasks.glslcc_clean]
workspace = false
script = "rm -rf external/glslcc/build"

[tasks.shaders_build]
workspace = false
condition = { files_modified = { input = [ "${CARGO_MAKE_WORKING_DIRECTORY}/external/glslcc/build/src/glslcc", "${CARGO_MAKE_WORKING_DIRECTORY}/shaders/src/**/*", ], output = [ "${CARGO_MAKE_WORKING_DIRECTORY}/shaders/build/**/*", ] } }
script = '''
GLSLCC="$CARGO_MAKE_WORKING_DIRECTORY/external/glslcc/build/src/glslcc"
BUILD="$CARGO_MAKE_WORKING_DIRECTORY/shaders/build"
SOURCE="$CARGO_MAKE_WORKING_DIRECTORY/shaders/src"

mkdir -p "$BUILD/120"
mkdir -p "$BUILD/330"
cd "$SOURCE"
for shader in *.frag *.vert;
do
    $GLSLCC -O -l glsl -p 120 -i "$shader" -o "$BUILD/120/$shader";
    $GLSLCC -O -l glsl -p 330 -i "$shader" -o "$BUILD/330/$shader";
done
'''

[tasks.shaders_clean]
workspace = false
script = "rm -rf shaders/build"

[tasks.pi_build]
workspace = false
script = "docker compose run -T --rm rust_pi bash -c 'cd /workspace && CMAKE_LIBRARY_PATH=/usr/lib/arm-linux-gnueabihf/ /root/.cargo/bin/cargo build --features pi --release --target-dir pi/target'"

[tasks.pi_clean]
workspace = false
script = "rm -rf pi/target"

[tasks.python_install]
workspace = false
script = "poetry install"

[tasks.python_clean]
workspace = false
script = "rm -rf .venv"

[tasks.ansible_install]
workspace = false
script = "poetry run ansible-galaxy collection install -r requirements.yml"

[tasks.ansible_clean]
workspace = false
script = "rm -rf ansible_collections"

[tasks.ansible_playbook]
workspace = false
script = "poetry run ansible-playbook playbook.yml ${@}"

[tasks.ansible_playbook_code]
workspace = false
script = "poetry run ansible-playbook playbook.yml --tags code ${@}"
