---

- name: config
  gather_facts: false
  hosts:
    - zero
    - localhost
  tags:
    - always
  tasks:
    - name: load config
      community.sops.load_vars:
        file: config.yml

- name: setup
  gather_facts: false
  hosts: zero
  tasks:
    - name: configure devices
      ansible.builtin.blockinfile:
        path: /boot/config.txt
        block: |
          [all]
          dtparam=i2c_arm=on
          dtparam=i2c_arm_baudrate=400000
          dtoverlay=pwm,pin=13,func=4
          gpu_mem=64
          dtoverlay=vc4-fkms-v3d
          max_framebuffers=2
          avoid_warnings=2
          hdmi_group=2
          hdmi_mode=87
          hdmi_cvt=240 240 60 1 0 0 0
          hdmi_force_hotplug=1
      notify: reboot

    - name: configure memory
      ansible.builtin.lineinfile:
        path: /boot/cmdline.txt
        backrefs: True
        regexp: '(^.+plymouth.ignore-serial-consoles)$'
        line: '\1 cma=128M@64M'
      notify: reboot

    - name: join bluetooth group
      ansible.builtin.user:
        name: pi
        groups: bluetooth
        append: true
      notify: reboot

    - name: check swap
      ansible.builtin.shell:
        cmd: cat /proc/swaps | tail -n +2
      changed_when: false
      register: swap_result

    - name: disable swap
      ansible.builtin.shell:
        cmd: "{{ item }}"
      loop:
        - dphys-swapfile swapoff
        - dphys-swapfile uninstall
      when: swap_result.stdout_lines|length > 0
      notify: reboot

    - name: configure journal
      community.general.ini_file:
        path: /etc/systemd/journald.conf
        section: Journal
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      loop:
        - option: Storage
          value: volatile
        - option: RuntimeMaxUse
          value: 15M
      notify: reboot

    - name: disable services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - dphys-swapfile
        - rsyslog
      notify: reboot

  handlers:
    - name: reboot
      ansible.builtin.reboot:
      listen: reboot

- name: deploy
  gather_facts: false
  hosts: zero
  tasks:
    - name: configure xorg
      ansible.builtin.copy:
        content: |
          Section "Monitor"
              Identifier "HDMI-1"
              Modeline "240x240" 4.19 240 248 264 288 240 243 253 256 -hsync +vsync
              Option "Rotate" "right"
          EndSection
          Section "Screen"
              Identifier "Screen-0"
              Device "Card0"
              Monitor "HDMI-1"
              SubSection "Display"
                  Virtual 320 240
                  Modes "240x240"
              EndSubSection
          EndSection
          Section "ServerLayout"
              Identifier "Layout-0"
              Screen "Screen-0" 0 0
          EndSection
          Section "ServerFlags"
              Option "BlankTime" "0"
          EndSection
        dest: /usr/share/X11/xorg.conf.d/10-deskpi.conf
        owner: root
        group: root
      notify: restart

    - name: stop service
      ansible.builtin.systemd:
        name: deskpi.service
        state: stopped
      ignore_errors: true
      notify: restart
      tags:
        - code

    - name: make directory
      ansible.builtin.file:
        path: /opt/deskpi
        owner: root
        group: root
        state: directory
      notify: restart

    - name: copy executable
      ansible.builtin.copy:
        src: pi/target/release/deskpi
        dest: /opt/deskpi/deskpi
        owner: root
        group: root
        mode: 'u=rwx,g=rx,o=rx'
      notify: restart
      tags:
        - code

    - name: configure service
      ansible.builtin.template:
        src: deskpi.service
        dest: /etc/systemd/system
        owner: root
        group: root
      notify: restart
      tags:
        - service

    - name: enable service
      ansible.builtin.systemd:
        name: deskpi
        enabled: true
      notify: restart

  handlers:
    - name: restart service
      ansible.builtin.systemd:
        daemon_reload: true
        name: deskpi.service
        state: restarted
      listen: restart
