[tool.poetry]
name = "deskpi"
version = "0.1.0"
description = ""
authors = ["Ricardo Matsui"]

[tool.poetry.dependencies]
python = "^3.10"
ansible = "^5.1.0"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
