---

- name: create mount point
  ansible.builtin.file:
    path: /media/circuit-playground
    state: directory
    owner: root
    group: root

- name: mount
  ansible.posix.mount:
    path: /media/circuit-playground
    src: LABEL=CIRCUITPY
    fstype: vfat
    opts: defaults,nofail,sync,noatime,umask=000
    state: mounted

- name: deploy
  ansible.builtin.copy:
    remote_src: false
    src: "{{ playbook_dir }}/circuit-playground/code.py"
    dest: /media/circuit-playground
  tags:
    - circuit_playground_code
