# https://github.com/tttapa/docker-arm-cross-toolchain?tab=readme-ov-file

[target.arm-unknown-linux-gnueabihf]
linker = "/opt/x-tools/armv6-rpi-linux-gnueabihf/bin/armv6-rpi-linux-gnueabihf-gcc"

rustflags = [
    "-C", "link-arg=--sysroot=/sysroot",
    "-C", "link-arg=-march=armv6",
    "-C", "link-arg=-mfpu=vfp",
    "-C", "link-arg=-mfloat-abi=hard",
    "-C", "target-cpu=arm1176jzf-s",
    "-L", "native=/sysroot/usr/lib/arm-linux-gnueabihf",
    "-L", "native=/sysroot/lib/arm-linux-gnueabihf",
    "-l", "systemd",
]
